CC = gcc

build: ./*.c ../common/getcmdinput.c
				$(CC) 1.c ../common/getcmdinput.c -o 1
				$(CC) 2.c ../common/getcmdinput.c -o 2
				$(CC) 3.c ../common/getcmdinput.c -o 3 -lm
				$(CC) 4.c ../common/getcmdinput.c -o 4 -lm
				
