CC = gcc
FLAGS = -Wall -pedantic -g
INPUTLIBPATH = ./common/getcmdinput.c

build: *.c
				$(CC) printBin.c $(INPUTLIBPATH) -o printBin $(FLAGS)
				$(CC) setBit.c $(INPUTLIBPATH) -o setBit $(FLAGS)
				$(CC) clearBit.c $(INPUTLIBPATH) -o clearBit $(FLAGS)
				$(CC) toggleBit.c $(INPUTLIBPATH) -o toggleBit $(FLAGS)
				$(CC) checkBit.c $(INPUTLIBPATH) -o checkBit $(FLAGS)
				$(CC) countBit.c $(INPUTLIBPATH) -o countBit $(FLAGS)
				$(CC) getRgb.c $(INPUTLIBPATH) -o getRgb $(FLAGS)
				$(CC) setRgb.c $(INPUTLIBPATH) -o setRgb $(FLAGS)

